DELAY : int = 5
WAIT : int  =  500
STOP: str = "stop"
OUT_OF_TOKENS: str = "<out_of_tokens>"
COMPLETION_MESSAGE: str = "chat.completion"
COMPLETION_CHUNK: str = "chat.completion.chunk"
MESSAGE_ID_PREFIX: str = "chatcmpl-"
PHIND_CODE_LLAMA = "Phind/Phind-CodeLlama-34B-v2"
CODE_LLAMA = "codellama/CodeLlama-13b-Instruct-hf"
